* gscholar bibtex
  [[http://melpa.org/#/gscholar-bibtex][file:http://melpa.org/packages/gscholar-bibtex-badge.svg]]

  Retrieve BibTeX entries from Google Scholar by your query. All in Emacs-lisp!
** Basic usage
  : (add-to-list 'load-path "/path/to/gscholar-bibtex.el")
  : (require 'gscholar-bibtex)
  : M-x gscholar-bibtex

  Then enter your query and select the results.

  Available commands in `gscholar-bibtex-mode', /i.e./, in the window of search
  results:
  - n/p: next/previous
  - TAB: show BibTeX entry for current search result
  - A/W: append/write to `gscholar-bibtex-database-file' (see later)
  - a/w: append/write to a file
  - c: close BibTeX entry window
  - q: quit

** Configure `gscholar-bibtex-database-file'
   If you have a master BibTeX file, say =refs.bib=, as database, and want to
   append/write the BibTeX entry to =refs.bib= without being asked for a
   filename to be written every time, you can set
   `gscholar-bibtex-database-file':
   : (setq gscholar-bibtex-database-file "/path/to/refs.bib")

   Then use "A" or "W" to append or write to =refs.bib=, respectively.
  
